### ISSUE TITLE
better method naming

### ISSUE THREAD

**Issue by derhuerst** [gulf/gulf#29]
When implementing `EditableDocument`, I found the method names to be quite difficult to understand. I suggest the following renaming:

- `_collectChanges` -> `onBeforeChange`
- `_change` -> `onChange`
- `_setContents` -> `setContent`

**Comment by marcelklehr** [comment]
I think this is a good idea! I was never really happy with the names.

**Comment by marcelklehr** [comment]
Current draft (in master) has

* `_collectChanges` -> `_onBeforeChange`
* `_change` -> `_onChange`
* `_setContents` -> `_setContent`

I opted to keep the underscores as that is in line with Node's stream API. Any feedback is appreciated.
