### ISSUE TITLE
Incremental integer identifiers for revisions

### ISSUE THREAD

**Issue by marcelklehr** [gulf/gulf#35]
Pro:
  - Easier to reason about logs
  - Easier to store (no graph-like structure necessary)
  - Easier and faster to retrieve (all revisions since x can be requested in parallel as x+1, x+2, etc.)

Con:
  - No branching possible (not strictly true, and would be even more terrible to implement with 4.x backends)

**Comment by marcelklehr** [comment]
Problem: Resend interval can cause the same edit to be received multiple times.

Resolution: Every edit gets a transmissionID, links store the last received transmissionID and drop all edits with the same transmissionID as the one in cache.

Gotcha: Reconnect and disconnect in short succession could result in assignment of new slave link before all resent edits have been transmitted -> the new slave link cannot identify the rest of them as already processed.

**Comment by derhuerst** [comment]
Just giving you input: Check https://github.com/noffle/hyper-string and https://github.com/noffle/textarea-op-stream !

**Comment by marcelklehr** [comment]
Thanks! I'm aware of CRDTs and noffle's projects. I have been [expe](https://github.com/marcelklehr/r-string)[rime](https://github.com/marcelklehr/peerpad)[nting](https://github.com/marcelklehr/lseq-between) as well. If you haven't already, check out https://github.com/Chat-Wane/CRATE ;)
