### ISSUE TITLE
lib directory missing from npm bundle

### ISSUE THREAD

**Issue by derhuerst** [gulf/gulf#37]
`npm info gulf version` returns `5.0.1`.

```shell
npm i gulf@latest
node -e 'require("gulf")'
```

```
﻿﻿﻿module.js:457
    throw err;
    ^

Error: Cannot find module 'gulf'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:556:32)
    at bootstrap_node.js:357:29
```

**`main` in `package.json` points to `./lib/index`, but `lib` is missing in `node_modules/gulf`.**

**Comment by derhuerst** [comment]
You can check what will be bundled using [`pkgfiles`](https://github.com/timoxley/pkgfiles).

**Comment by derhuerst** [comment]
I'd suggest to put a [`files` field](https://docs.npmjs.com/files/package.json#files) into your `package.json`, with `["lib/*"]`.

**Comment by g-borgulya** [comment]
I have the same problem. I have no idea what the lib/ dir would be for - maybe I don't get an important point?

But changing 
```"main": "./lib/index",```
to
```"main": "./src/index",```
in package.json seems to solve the issue.

**Comment by derhuerst** [comment]
`src` contains the untranspiled ES20xx source code. `lib` contains the source code [transpired by Babel](https://github.com/gulf/gulf/blob/5d6131bd0bbb93e8711ed24ccb50f5ac45457c77/package.json#L32).

Although it's a matter of taste and Node.js installations are usually more up to date than browsers (in terms off market share), I'd prefer to bundle `lib`, to make gulf compatible with node `<=4`.

**Comment by marcelklehr** [comment]
Thanks for the heads up!

**Comment by derhuerst** [comment]
How did 	f9c87b4 fix this? It still doesn't work. (Still, using a whitelist is safer. :wink:)

**Comment by marcelklehr** [comment]
I'm not sure from your comment if it works for you now. Does it? (It works for me.)

**Comment by derhuerst** [comment]
It does, even though `pkgfiles` shows that npm wouldn't publish `lib`, but `src` instead:

```
PATH                                SIZE       %   
.npmignore                          0 B        0%  
.zuul.yml                           328 B      0%  
src/index.js                        345 B      0%  
.travis.yml                         512 B      0%  
test/helper/parallelmaster_fork.js  769 B      1%  
src/MemoryAdapter.js                1.37 kB    1%  
package.json                        1.42 kB    1%  
src/Revision.js                     3.62 kB    3%  
src/EditableDocument.js             5.69 kB    5%  
src/Link.js                         7.91 kB    7%  
src/Document.js                     10.46 kB   9%  
test/tests.js                       14.46 kB   12% 
test/tests.es5.js                   15.58 kB   13% 
README.md                           17.34 kB   15% 
LICENSE.txt                         39.34 kB   33% 
                                                   
DIR                                 SIZE       %   
test/helper/                        769 B      1%  
src/                                29.39 kB   25% 
test/                               30.81 kB   26% 
.                                   119.15 kB  100%

PKGFILES SUMMARY
Size on Disk with Dependencies  ~544.77 kB
Size with Dependencies          ~428.12 kB
Publishable Size                ~119.15 kB
Number of Directories           4         
Number of Files                 15        
```

**Comment by marcelklehr** [comment]
From https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package :
> Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it. Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory.

**Comment by derhuerst** [comment]
I know that behaviour. Sounds a lot like a bug in `pkgfiles`. Submitted timoxley/pkgfiles#10.

Is there a particular reason you bundled `src/`?

**Comment by marcelklehr** [comment]
I saw no reason not to. If in doubt I like to package the source files as well, even more so since browserify etc. only include the explicitly `require`d files anyway. I'm open to changing this, though, if this poses a problem.

**Comment by derhuerst** [comment]
It's not an explicit problem. It rather that, implicitly, non-minimal NPM bundles make dependency trees of JS projects a lot larger. We already talking about thousands of files (megabytes in size), even for small projects.

That's why it seems to be common to bundle what is really necessary, as the `package.json` in the bundle contains the git hash that was published anyway. I came across only one exception: https://github.com/thlorenz/cardinal/pull/21#issuecomment-253708821 .

**Comment by marcelklehr** [comment]
Makes sense to me -> Done.
