### ISSUE TITLE
Gulf v5 Mongoskin Adapter

### ISSUE THREAD

**Issue by CallForSanity** [gulf/gulf#38]
Hi,

we (the Evocracy project) have written and tested a gulf-mongoskin adapter for gulf v5.
After failing to port the prexisting mongoose adapter from v4 to v5
we have decided to use mongoskin as a basis instead.

Check it out:
[https://github.com/openevocracy/gulf-mongoskin](url)

We hope this will help someone.

Best Regards,
Patrick

**Comment by marcelklehr** [comment]
Awesome. I'll link to it in the README :)
